name: update swagger
run-name: update swagger

on:
  schedule:
    - cron:  '0 */12 * * *' # every 12 hours on the hour
  workflow_dispatch:

jobs:
  update-swagger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          wget https://github.com/go-gitea/gitea/blob/main/templates/swagger/v1_json.tmpl
          sed -i "$@" 's/"version": "{{AppVer | JSEscape | Safe}}"/"version": "dev"/' static/swagger-latest.json
          rm v1_json.tmpl

          wget https://github.com/go-gitea/gitea/blob/v1.22.2/templates/swagger/v1_json.tmpl
          sed -i "$@" 's/"version": "{{AppVer | JSEscape | Safe}}"/"version": "1.22.2"/' static/swagger-1.22.json

      - name: push swagger to repo
        uses: appleboy/git-push-action@v0.0.3
        with:
          author_email: "teabot@gitea.io"
          author_name: GiteaBot
          branch: main
          commit: true
          commit_message: "[skip ci] Updated swagger files"
          remote: "git@gitea.com:gitea/docs.git"
          ssh_key: ${{ secrets.DEPLOY_KEY }}
